
Vagrant.configure(2) do |config|
  config.vm.box = "modernIE/w7-ie11"
  config.vm.guest = :windows
  config.vm.hostname = "FSE-2010-PAT-RTS"
  config.vm.communicator = "winrm"

  config.vm.provider "virtualbox" do |vb|
	 vb.name = "FSE-2010-PAT-RTS"
     vb.gui = true
     vb.memory = "1024"
  end

  config.vm.provision :shell, path: "scripts/chocolatey.bat"
  config.vm.provision :shell, path: "scripts/dotnet.bat"
  config.vm.provision :shell, path: "scripts/PAT.bat"
  config.vm.provision :shell, path: "scripts/desktop.bat"
  
  config.vm.provision :windows_reboot
  
end
